# Pollution Controls Data Cleaning & Transformation

## Objective
Clean and transform pollution monitoring data to improve data quality and generate meaningful insights.

## Technologies Used
- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn

#### Importing the Required Libraries

In [697]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [698]:
df=pd.read_csv("pollution_raw_data.csv",encoding='latin1')

In [699]:
df

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS,PM2_5,SO2,NOx,Unit,LatLon,...,Wind_speed_m_s,Wind_dir_deg,Temp_C,RH_pct,Jurisdiction,Regulation_version,Pollutant_standard_hourly,Pollutant_standard_daily,Raw_note,Inspector_notes
0,E103669,PL-11,ST-035,stack,08-03-2026 19:28,59.101,39.112,89.258,ug/m3,"14.4257, 79.5948",...,13.05,202.7,15.6,31.1,Tamil Nadu,CPCB-2025,116.8,86.2,contains pii: John Doe,no issues observed
1,E114788,PL-05,ST-038,ambient,31-03-2026 14:14,83.134,26.186,27.840,UG/M3,"15.5940 , 79.9476",...,13.18,157.8,17.5,56.8,Tamil Nadu,CPCB-2025,65.0,50.8,manual note,NaN
2,E112496,PL-10,ST-036,lab,26-03-2026 21:23,299.073,59.344,29.127,mg/Nm3,"13.6265, 78.4542",...,2.62,37.3,23.8,70.6,Maharashtra,CPCB-2025,190.6,70.8,contains pii: John Doe,contact Mr. X
3,E103781,PL-04,ST-007,stack,09-03-2026 24:52,39.035,24.661,56.553,Âµg/mÂ³,"13.9342, 76.9687",...,12.85,60.4,29.0,84.1,Maharashtra,CPCB-2023,157.1,98.8,manual note,NaN
4,E100116,PL-06,ST-003,lab,01-03-2026 06:15,146.540,47.534,48.502,mg/nm3,"14.7164, 80.5555",...,12.84,60.3,18.5,54.7,Tamil Nadu,CPCB-2025,156.8,53.2,OK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15245,E105191,PL-11,ST-035,ambient,11-03-2026 20:28,158.509,9.663,40.921,ug/m3,"14.4257, 79.5948",...,11.70,220.9,23.6,91.7,Maharashtra,CPCB-2023,130.7,79.3,inspection note,contact Mr. X
15246,E113418,PL-09,ST-039,stack,28-03-2026 17:28,44.551,53.984,28.461,UG/M3,"13.3116 , 81.6812",...,9.97,171.1,18.1,68.8,Karnataka,CPCB-2024,59.7,41.0,contains pii: John Doe,stack access restricted
15247,E105390,PL-17,ST-014,stack,12-03-2026 07:11,355.883,41.063,65.655,UG/M3,"13.4940, 76.0448",...,9.23,195.0,28.5,84.8,Tamil Nadu,CPCB-2024,51.7,89.5,inspection note,NaN
15248,E100860,PL-06,ST-003,stack,02-03-2026 19:14,175.051,62.552,43.249,Âµg/mÂ³,"14.7164, 80.5555",...,8.80,314.6,19.9,74.7,Tamil Nadu,CPCB-2025,179.3,40.2,inspection note,contact Mr. X
15249,E107270,PL-10,ST-036,inspection,16-03-2026 04:39,89.395,160.166,56.575,mg/Nm3,"13.6265, 78.4542",...,12.05,135.8,35.8,60.9,Tamil Nadu,CPCB-2023,101.4,40.3,manual note,no issues observed

In [700]:
df.head(10)

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS,PM2_5,SO2,NOx,Unit,LatLon,...,Wind_speed_m_s,Wind_dir_deg,Temp_C,RH_pct,Jurisdiction,Regulation_version,Pollutant_standard_hourly,Pollutant_standard_daily,Raw_note,Inspector_notes
0,E103669,PL-11,ST-035,stack,08-03-2026 19:28,59.101,39.112,89.258,ug/m3,"14.4257, 79.5948",...,13.05,202.7,15.6,31.1,Tamil Nadu,CPCB-2025,116.8,86.2,contains pii: John Doe,no issues observed
1,E114788,PL-05,ST-038,ambient,31-03-2026 14:14,83.134,26.186,27.840,UG/M3,"15.5940 , 79.9476",...,13.18,157.8,17.5,56.8,Tamil Nadu,CPCB-2025,65.0,50.8,manual note,NaN
2,E112496,PL-10,ST-036,lab,26-03-2026 21:23,299.073,59.344,29.127,mg/Nm3,"13.6265, 78.4542",...,2.62,37.3,23.8,70.6,Maharashtra,CPCB-2025,190.6,70.8,contains pii: John Doe,contact Mr. X
3,E103781,PL-04,ST-007,stack,09-03-2026 24:52,39.035,24.661,56.553,Âµg/mÂ³,"13.9342, 76.9687",...,12.85,60.4,29.0,84.1,Maharashtra,CPCB-2023,157.1,98.8,manual note,NaN
4,E100116,PL-06,ST-003,lab,01-03-2026 06:15,146.540,47.534,48.502,mg/nm3,"14.7164, 80.5555",...,12.84,60.3,18.5,54.7,Tamil Nadu,CPCB-2025,156.8,53.2,OK,NaN
5,E114407,PL-18,ST-007,ambient,30-03-2026 19:30,127.864,30.846,56.044,mg/nm3,"13.1283, 77.9525",...,14.37,48.7,41.8,68.7,Karnataka,CPCB-2023,170.2,65.5,manual note,no issues observed
6,E108881,PL-19,ST-006,stack,19-03-2026 11:05,441.111,14.619,151.803,ug/m3,"13.3429, 80.2667",...,8.69,241.6,20.1,52.6,Karnataka,CPCB-2024,141.1,84.6,OK,contact Mr. X
7,E111524,PL-18,ST-007,stack,24-03-2026 19:24,129.840,42.299,106.759,mg/nm3,"13.1283, 77.9525",...,7.38,4.2,17.4,64.2,Tamil Nadu,CPCB-2023,72.4,90.5,OK,stack access restricted
8,E101606,PL-18,ST-022,lab,04-03-2026 10:07,123.836,99999.000,51.405,UG/M3,"13.1283, 77.9525",...,14.32,106.1,25.6,50.0,Odisha,CPCB-2023,144.5,39.5,OK,no issues observed
9,E110447,PL-16,ST-022,stack,22-03-2026 15:50,68.047,59.063,46.950,mg/Nm3,"15.9548, 82.5124",...,0.49,290.6,37.3,68.8,Karnataka,CPCB-2023,87.7,40.1,OK,contact Mr. X

In [701]:
df.tail(10)

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS,PM2_5,SO2,NOx,Unit,LatLon,...,Wind_speed_m_s,Wind_dir_deg,Temp_C,RH_pct,Jurisdiction,Regulation_version,Pollutant_standard_hourly,Pollutant_standard_daily,Raw_note,Inspector_notes
15240,E100466,PL-08,ST-015,inspection,01-03-2026 23:59,102.304,15.093,71.721,ug/m3,"15.2354, 77.0165",...,12.93,119.1,18.3,78.0,Maharashtra,CPCB-2023,104.0,88.5,contains pii: John Doe,contact Mr. X
15241,E106265,PL-14,ST-018,stack,14-03-2026 02:31,202.027,7.809,88.906,Âµg/mÂ³,"13.8778, 78.5787",...,2.70,101.9,38.1,40.9,Karnataka,CPCB-2023,107.9,32.6,OK,contact Mr. X
15242,E105734,PL-20,ST-023,ambient,12-03-2026 23:44,74.634,47.466,77.673,Âµg/mÂ³,"15.5740, 81.8940",...,12.70,307.8,18.3,23.5,Maharashtra,CPCB-2025,167.8,73.9,manual note,NaN
15243,E111284,PL-11,ST-035,stack,24-03-2026 08:03,65.841,25.037,21.910,Âµg/mÂ³,"14.4257, 79.5948",...,15.00,211.7,20.3,36.8,Odisha,CPCB-2025,95.2,43.1,contains pii: John Doe,contact Mr. X
15244,E111964,PL-13,ST-038,lab,25-03-2026 18:51,77.146,NaN,33.863,ug/m3,"14.9332, 81.7124",...,1.70,306.1,27.1,27.1,Tamil Nadu,CPCB-2023,104.8,52.9,manual note,NaN
15245,E105191,PL-11,ST-035,ambient,11-03-2026 20:28,158.509,9.663,40.921,ug/m3,"14.4257, 79.5948",...,11.70,220.9,23.6,91.7,Maharashtra,CPCB-2023,130.7,79.3,inspection note,contact Mr. X
15246,E113418,PL-09,ST-039,stack,28-03-2026 17:28,44.551,53.984,28.461,UG/M3,"13.3116 , 81.6812",...,9.97,171.1,18.1,68.8,Karnataka,CPCB-2024,59.7,41.0,contains pii: John Doe,stack access restricted
15247,E105390,PL-17,ST-014,stack,12-03-2026 07:11,355.883,41.063,65.655,UG/M3,"13.4940, 76.0448",...,9.23,195.0,28.5,84.8,Tamil Nadu,CPCB-2024,51.7,89.5,inspection note,NaN
15248,E100860,PL-06,ST-003,stack,02-03-2026 19:14,175.051,62.552,43.249,Âµg/mÂ³,"14.7164, 80.5555",...,8.80,314.6,19.9,74.7,Tamil Nadu,CPCB-2025,179.3,40.2,inspection note,contact Mr. X
15249,E107270,PL-10,ST-036,inspection,16-03-2026 04:39,89.395,160.166,56.575,mg/Nm3,"13.6265, 78.4542",...,12.05,135.8,35.8,60.9,Tamil Nadu,CPCB-2023,101.4,40.3,manual note,no issues observed

In [702]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15250 entries, 0 to 15249
Data columns (total 41 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Record_ID                  15250 non-null  object
 1   Plant_ID                   15250 non-null  object
 2   Stack_ID                   15250 non-null  object
 3   Source_Type                15250 non-null  object
 4   TS                         15250 non-null  object
 5   PM2_5                      14943 non-null  float64
 6   SO2                        14926 non-null  float64
 7   NOx                        14970 non-null  float64
 8   Unit                       15250 non-null  object
 9   LatLon                     15250 non-null  object
 10  Status                     15250 non-null  object
 11  Sensor_serial              15250 non-null  object
 12  Instrument_type            15250 non-null  object
 13  Manufacturer               15250 non-null  object
 14  Calibration_span_factor    15250 non-null  float64
 15  Calibration_zero_offset    15250 non-null  float64
 16  Last_calibration_ts        10706 non-null  object
 17  Next_calibration_due       10681 non-null  object
 18  LOD_PM2_5                  15250 non-null  float64
 19  LOD_SO2                    15250 non-null  float64
 20  LOD_NOx                    15250 non-null  float64
 21  Maintenance_event_ID       1194 non-null   object
 22  Maintenance_start_ts       1194 non-null   object
 23  Maintenance_end_ts         1194 non-null   object
 24  Maintenance_type           1194 non-null   object
 25  Maintenance_notes          896 non-null    object
 26  Lab_sample_ID              2334 non-null   object
 27  Lab_received_ts            2334 non-null   object
 28  Lab_result_entry_ts        2334 non-null   object
 29  Analyst_ID                 2334 non-null   object
 30  Double_entry_check_flag    2334 non-null   float64
 31  Wind_speed_m_s             15250 non-null  float64
 32  Wind_dir_deg               15250 non-null  float64
 33  Temp_C                     15250 non-null  float64
 34  RH_pct                     15250 non-null  float64
 35  Jurisdiction               15250 non-null  object
 36  Regulation_version         15250 non-null  object
 37  Pollutant_standard_hourly  15250 non-null  float64
 38  Pollutant_standard_daily   15250 non-null  float64
 39  Raw_note                   15250 non-null  object
 40  Inspector_notes            11544 non-null  object
dtypes: float64(15), object(26)
memory usage: 4.8+ MB

In [703]:
df.describe()

,PM2_5,SO2,NOx,Calibration_span_factor,Calibration_zero_offset,LOD_PM2_5,LOD_SO2,LOD_NOx,Double_entry_check_flag,Wind_speed_m_s,Wind_dir_deg,Temp_C,RH_pct,Pollutant_standard_hourly,Pollutant_standard_daily
count,14943.000000,14926.000000,14970.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000,2334.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000
mean,138.556204,585.147477,54.623531,1.014270,0.002284,5.509156,2.993194,4.523609,0.502999,7.539279,181.213292,25.965272,59.124485,125.370275,62.300892
std,114.895895,7389.161033,38.777999,0.037453,1.153595,2.598134,1.153691,2.026407,0.500098,4.352090,104.248739,9.203667,22.400592,43.190086,21.679210
min,-862.202000,3.919000,0.000000,0.950000,-1.999900,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,10.000000,20.000000,50.000000,25.000000
25%,67.164500,20.072500,28.592000,0.981800,-1.007500,3.250000,2.000000,2.780000,0.000000,3.700000,91.400000,18.000000,39.600000,88.000000,43.000000
50%,110.312000,29.987000,44.628500,1.014000,0.013700,5.510000,2.990000,4.540000,1.000000,7.580000,181.200000,25.900000,59.200000,125.300000,62.200000
75%,177.364000,45.234750,68.461500,1.046500,0.997200,7.770000,3.990000,6.280000,1.000000,11.327500,273.000000,33.900000,78.300000,162.700000,81.000000
max,1336.658000,99999.000000,436.078000,1.080000,1.999600,10.000000,5.000000,8.000000,1.000000,15.000000,360.000000,42.000000,98.000000,200.000000,100.000000

In [704]:
df.describe(include='object')

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS,Unit,LatLon,Status,Sensor_serial,Instrument_type,...,Maintenance_type,Maintenance_notes,Lab_sample_ID,Lab_received_ts,Lab_result_entry_ts,Analyst_ID,Jurisdiction,Regulation_version,Raw_note,Inspector_notes
count,15250,15250,15250,15250,15250,15250,15250,15250,15250,15250,...,1194,896,2334,2334,2334,2334,15250,15250,15250,11544
unique,15000,20,25,4,12807,5,61,9,13791,3,...,4,3,2290,2294,2291,2000,4,3,4,3
top,E113420,PL-15,ST-007,stack,06-03-2026 03:34,ug/m3,"14.3140, 78.4597",fault,SN69616,AQI,...,corrective,zero drift noted,LS535497,2026-03-23 11:25:49,2026-03-20 15:56:23,AN3568,Tamil Nadu,CPCB-2025,OK,no issues observed
freq,3,806,1184,8430,5,3092,727,2253,5,5099,...,318,320,2,2,3,4,3862,5117,3854,3903

In [705]:
df.shape

(15250, 41)

In [706]:
df.columns

Index(['Record_ID', 'Plant_ID', 'Stack_ID', 'Source_Type', 'TS', 'PM2_5',
       'SO2', 'NOx', 'Unit', 'LatLon', 'Status', 'Sensor_serial',
       'Instrument_type', 'Manufacturer', 'Calibration_span_factor',
       'Calibration_zero_offset', 'Last_calibration_ts',
       'Next_calibration_due', 'LOD_PM2_5', 'LOD_SO2', 'LOD_NOx',
       'Maintenance_event_ID', 'Maintenance_start_ts', 'Maintenance_end_ts',
       'Maintenance_type', 'Maintenance_notes', 'Lab_sample_ID',
       'Lab_received_ts', 'Lab_result_entry_ts', 'Analyst_ID',
       'Double_entry_check_flag', 'Wind_speed_m_s', 'Wind_dir_deg', 'Temp_C',
       'RH_pct', 'Jurisdiction', 'Regulation_version',
       'Pollutant_standard_hourly', 'Pollutant_standard_daily', 'Raw_note',
       'Inspector_notes'],
      dtype='object')

In [707]:
print(df.columns.tolist())

['Record_ID', 'Plant_ID', 'Stack_ID', 'Source_Type', 'TS', 'PM2_5', 'SO2', 'NOx', 'Unit', 'LatLon', 'Status', 'Sensor_serial', 'Instrument_type', 'Manufacturer', 'Calibration_span_factor', 'Calibration_zero_offset', 'Last_calibration_ts', 'Next_calibration_due', 'LOD_PM2_5', 'LOD_SO2', 'LOD_NOx', 'Maintenance_event_ID', 'Maintenance_start_ts', 'Maintenance_end_ts', 'Maintenance_type', 'Maintenance_notes', 'Lab_sample_ID', 'Lab_received_ts', 'Lab_result_entry_ts', 'Analyst_ID', 'Double_entry_check_flag', 'Wind_speed_m_s', 'Wind_dir_deg', 'Temp_C', 'RH_pct', 'Jurisdiction', 'Regulation_version', 'Pollutant_standard_hourly', 'Pollutant_standard_daily', 'Raw_note', 'Inspector_notes']

In [708]:
# df.loc[[3,13,26,48,80],['TS']]

In [709]:
print("Before Datetime Normalization:")
print(df["TS"].head())

ts = df["TS"].astype(str).str.strip()

mask_24 = ts.str.contains(" 24:", na=False)

ts = ts.str.replace(" 24:", " 00:", regex=False)

df["TS"] = pd.to_datetime(
    ts,
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

df.loc[mask_24, "TS"] = df.loc[mask_24, "TS"] + pd.Timedelta(days=1)

print("\nAfter Datetime Normalization:")
print(df["TS"].head())

print("\nMissing datetime values:", df["TS"].isna().sum())

Before Datetime Normalization:
0    08-03-2026 19:28
1    31-03-2026 14:14
2    26-03-2026 21:23
3    09-03-2026 24:52
4    01-03-2026 06:15
Name: TS, dtype: object

After Datetime Normalization:
0   2026-03-08 19:28:00
1   2026-03-31 14:14:00
2   2026-03-26 21:23:00
3   2026-03-10 00:52:00
4   2026-03-01 06:15:00
Name: TS, dtype: datetime64[ns]

Missing datetime values: 0

In [710]:
# df.loc[[3,13,26,48,80],['TS']]

In [711]:
print("Before Standardization:")
print(df["Unit"].unique())

df["Unit"] = (
    df["Unit"].astype(str).str.strip().replace({
        "Âµg/mÂ³": "ug/m3",
        "UG/M3": "ug/m3",
        "mg/nm3": "mg/Nm3"
    })
)

print("\nAfter Standardization:")
print(df["Unit"].unique())

print("\nUnit Counts:")
print(df["Unit"].value_counts())

Before Standardization:
['ug/m3' 'UG/M3' 'mg/Nm3' 'Âµg/mÂ³' 'mg/nm3']

After Standardization:
['ug/m3' 'mg/Nm3']

Unit Counts:
Unit
ug/m3     9123
mg/Nm3    6127
Name: count, dtype: int64

In [712]:
print("Before Parsing:")
print(df["LatLon"].head())

df[["Latitude", "Longitude"]] = df["LatLon"].str.split(",", expand=True)

df["Latitude"] = df["Latitude"].str.strip()
df["Longitude"] = df["Longitude"].str.strip()

df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")

df.loc[(df["Latitude"] < -90) | (df["Latitude"] > 90), "Latitude"] = pd.NA
df.loc[(df["Longitude"] < -180) | (df["Longitude"] > 180), "Longitude"] = pd.NA

print("\nAfter Parsing:")
print(df[["Latitude", "Longitude"]].head())

print("\nMissing Latitude:", df["Latitude"].isnull().sum())
print("Missing Longitude:", df["Longitude"].isnull().sum())

Before Parsing:
0       14.4257, 79.5948
1     15.5940 , 79.9476
2       13.6265, 78.4542
3       13.9342, 76.9687
4       14.7164, 80.5555
Name: LatLon, dtype: object

After Parsing:
   Latitude  Longitude
0   14.4257    79.5948
1   15.5940    79.9476
2   13.6265    78.4542
3   13.9342    76.9687
4   14.7164    80.5555

Missing Latitude: 0
Missing Longitude: 0

In [713]:
print("Negative PM2.5 values:", (df["PM2_5"] < 0).sum())
print("Impossible SO2 values (99999):", (df["SO2"] == 99999).sum())
print("NOx values equal to 0:", (df["NOx"] == 0).sum())

df.loc[df["PM2_5"] < 0, "PM2_5"] = pd.NA

df.loc[df["SO2"] == 99999, "SO2"] = pd.NA

df.loc[df["NOx"] == 0, "NOx"] = pd.NA

print("\nAfter Cleaning:")
print("Negative PM2.5 values:", (df["PM2_5"] < 0).sum())
print("Impossible SO2 values (99999):", (df["SO2"] == 99999).sum())
print("NOx values equal to 0:", (df["NOx"] == 0).sum())

print("\nMissing Values:")
print(df[["PM2_5", "SO2", "NOx"]].isnull().sum())

Negative PM2.5 values: 148
Impossible SO2 values (99999): 82
NOx values equal to 0: 63

After Cleaning:
Negative PM2.5 values: 0
Impossible SO2 values (99999): 0
NOx values equal to 0: 0

Missing Values:
PM2_5    455
SO2      406
NOx      343
dtype: int64

In [714]:
print("Duplicates Before Merging:")
print(df.duplicated(subset=["Plant_ID", "TS"]).sum())

df = df.groupby(["Plant_ID", "TS"], as_index=False).first()

print("\nDuplicates After Merging:")
print(df.duplicated(subset=["Plant_ID", "TS"]).sum())

print("\nDataset Shape:")
print(df.shape)

print("\nSample Data:")
print(df[["Plant_ID", "TS"]].head())

Duplicates Before Merging:
367

Duplicates After Merging:
0

Dataset Shape:
(14883, 43)

Sample Data:
  Plant_ID                  TS
0    PL-01 2026-03-01 00:48:00
1    PL-01 2026-03-01 06:29:00
2    PL-01 2026-03-01 10:00:00
3    PL-01 2026-03-01 10:05:00
4    PL-01 2026-03-01 10:24:00

In [715]:
print("Before Calibration:")
print(df[["PM2_5", "SO2", "NOx"]].head())

df["PM2_5"] = (df["PM2_5"] * df["Calibration_span_factor"]) + df["Calibration_zero_offset"]

df["SO2"] = (df["SO2"] * df["Calibration_span_factor"]) + df["Calibration_zero_offset"]

df["NOx"] = (df["NOx"] * df["Calibration_span_factor"]) + df["Calibration_zero_offset"]

df["PM2_5"] = df["PM2_5"].round(2)
df["SO2"] = df["SO2"].round(2)
df["NOx"] = df["NOx"].round(2)

print("\nAfter Calibration:")
print(df[["PM2_5", "SO2", "NOx"]].head())

Before Calibration:
     PM2_5     SO2      NOx
0  157.841  50.282   26.061
1   83.868  29.843   35.493
2  155.719  18.323      NaN
3  153.279  62.153   28.007
4   71.153  11.059  122.411

After Calibration:
    PM2_5    SO2     NOx
0  151.17  47.67   24.36
1   86.04  29.92   35.79
2  166.85  20.62     NaN
3  164.12  66.24   29.57
4   76.24  12.63  130.50

In [716]:
print("Before Filtering:")
print(df["PM2_5"].head(10))

rolling_median = df["PM2_5"].rolling(window=5, center=True).median()

mad = (df["PM2_5"] - rolling_median).abs().rolling(window=5, center=True).median()

threshold = 3 * 1.4826 * mad

outliers = (df["PM2_5"] - rolling_median).abs() > threshold

df.loc[outliers, "PM2_5"] = rolling_median[outliers]

print("\nAfter Filtering:")
print(df["PM2_5"].head(10))

print("\nOutliers Corrected:", outliers.sum())

Before Filtering:
0    151.17
1     86.04
2    166.85
3    164.12
4     76.24
5    293.89
6     56.38
7    149.14
8    125.15
9    116.68
Name: PM2_5, dtype: float64

After Filtering:
0    151.17
1     86.04
2    166.85
3    164.12
4     76.24
5    293.89
6     56.38
7    149.14
8    125.15
9    116.68
Name: PM2_5, dtype: float64

Outliers Corrected: 1255