# Pollution Controls Data Cleaning & Transformation

## Objective
Clean and transform pollution monitoring data to improve data quality and generate meaningful insights.

## Technologies Used
- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn

#### Importing the Required Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("pollution_raw_data.csv", encoding='latin1')

# Parse overflowed clock times (for example, 24:10 becomes 00:10 on the next day).
ts_parts = df['TS'].astype('string').str.extract(r'^\s*(\d{2}-\d{2}-\d{4})\s+(\d{1,2}):(\d{2})\s*$')
ts_date = pd.to_datetime(ts_parts[0], format='%d-%m-%Y', errors='coerce')
ts_hours = pd.to_numeric(ts_parts[1], errors='coerce')
ts_minutes = pd.to_numeric(ts_parts[2], errors='coerce')
df['TS_normalized'] = ts_date + pd.to_timedelta(ts_hours, unit='h') + pd.to_timedelta(ts_minutes, unit='m')

In [3]:
df

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS_raw,TS_local,TS_utc,TS_timezone,PM2_5_raw,PM2_5_unit,...,RH_pct,Jurisdiction,Regulation_version,Pollutant_standard_hourly,Pollutant_standard_daily,Ingest_ts,Source_file,Source_row_num,Raw_note,Inspector_notes
0,E103669,PL-09,ST-039,lab,08-03-2026 19:28,2026-03-08 19:28:52,2026-03-08T13:58:52Z,Asia/Kolkata,59.101,mg/nm3,...,31.1,Odisha,CPCB-2025,116.8,86.2,2026-07-23 10:56:00,cems_batch_19.csv,3670,inspection note,contact Mr. X
1,E114788,PL-11,ST-035,stack,31-03-2026 14:14,2026-03-31 14:14:25,2026-03-31T08:44:25Z,Asia/Kolkata,83.134,ug/m3,...,56.8,Odisha,CPCB-2025,65.0,50.8,2026-07-23 10:56:00,cems_batch_02.csv,14789,manual note,NaN
2,E112496,PL-10,ST-036,inspection,26-03-2026 21:23,2026-03-26 21:23:55,2026-03-26T15:53:55Z,Asia/Kolkata,299.073,Âµg/mÂ³,...,70.6,Tamil Nadu,CPCB-2025,190.6,70.8,2026-07-23 10:56:00,cems_batch_14.csv,12497,contains pii: John Doe,NaN
3,E103781,PL-09,ST-033,ambient,09-03-2026 00:52,2026-03-09 00:52:15,2026-03-08T19:22:15Z,Asia/Kolkata,39.035,Âµg/mÂ³,...,84.1,Odisha,CPCB-2024,157.1,98.8,2026-07-23 10:56:00,cems_batch_07.csv,3782,OK,no issues observed
4,E103450,PL-04,ST-007,ambient,08-03-2026 08:18,2026-03-08 08:18:56,2026-03-08T02:48:56Z,Asia/Kolkata,70.639,mg/nm3,...,63.5,Odisha,CPCB-2024,146.2,79.9,2026-07-23 10:56:00,cems_batch_15.csv,103451,OK,contact Mr. X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15245,E105191,PL-13,ST-029,stack,11-03-2026 20:28,2026-03-11 20:28:07,2026-03-11T14:58:07Z,Asia/Kolkata,158.509,Âµg/mÂ³,...,91.7,Tamil Nadu,CPCB-2025,130.7,79.3,2026-07-23 10:56:00,cems_batch_01.csv,5192,contains pii: John Doe,stack access restricted
15246,E113418,PL-04,ST-035,stack,28-03-2026 17:28,2026-03-28 17:28:02,2026-03-28T11:58:02Z,Asia/Kolkata,44.551,Âµg/mÂ³,...,68.8,Maharashtra,CPCB-2023,59.7,41.0,2026-07-23 10:56:00,cems_batch_04.csv,13419,OK,contact Mr. X
15247,E105390,PL-17,ST-010,stack,2026/03/12 07:11:04,2026-03-12 07:11:04,2026-03-12T01:41:04Z,Asia/Kolkata,-355.883,Âµg/mÂ³,...,84.8,Odisha,CPCB-2024,51.7,89.5,2026-07-23 10:56:00,cems_batch_13.csv,5391,inspection note,contact Mr. X
15248,E100860,PL-01,ST-002,stack,02-03-2026 19:14,2026-03-02 19:14:07,2026-03-02T13:44:07Z,Asia/Kolkata,175.051,ug/m3,...,74.7,Karnataka,CPCB-2023,179.3,40.2,2026-07-23 10:56:00,cems_batch_08.csv,861,contains pii: John Doe,no issues observed
15249,E107270,PL-10,ST-036,stack,16-03-2026 04:39,2026-03-16 04:39:03,2026-03-15T23:09:03Z,Asia/Kolkata,89.395,Âµg/mÂ³,...,60.9,Odisha,CPCB-2023,101.4,40.3,2026-07-23 10:56:00,cems_batch_14.csv,7271,inspection note,contact Mr. X

In [6]:
df.head(10)

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS_raw,TS_local,TS_utc,TS_timezone,PM2_5_raw,PM2_5_unit,...,RH_pct,Jurisdiction,Regulation_version,Pollutant_standard_hourly,Pollutant_standard_daily,Ingest_ts,Source_file,Source_row_num,Raw_note,Inspector_notes
0,E103669,PL-09,ST-039,lab,08-03-2026 19:28,2026-03-08 19:28:52,2026-03-08T13:58:52Z,Asia/Kolkata,59.101,mg/nm3,...,31.1,Odisha,CPCB-2025,116.8,86.2,2026-07-23 10:56:00,cems_batch_19.csv,3670,inspection note,contact Mr. X
1,E114788,PL-11,ST-035,stack,31-03-2026 14:14,2026-03-31 14:14:25,2026-03-31T08:44:25Z,Asia/Kolkata,83.134,ug/m3,...,56.8,Odisha,CPCB-2025,65.0,50.8,2026-07-23 10:56:00,cems_batch_02.csv,14789,manual note,NaN
2,E112496,PL-10,ST-036,inspection,26-03-2026 21:23,2026-03-26 21:23:55,2026-03-26T15:53:55Z,Asia/Kolkata,299.073,Âµg/mÂ³,...,70.6,Tamil Nadu,CPCB-2025,190.6,70.8,2026-07-23 10:56:00,cems_batch_14.csv,12497,contains pii: John Doe,NaN
3,E103781,PL-09,ST-033,ambient,09-03-2026 00:52,2026-03-09 00:52:15,2026-03-08T19:22:15Z,Asia/Kolkata,39.035,Âµg/mÂ³,...,84.1,Odisha,CPCB-2024,157.1,98.8,2026-07-23 10:56:00,cems_batch_07.csv,3782,OK,no issues observed
4,E103450,PL-04,ST-007,ambient,08-03-2026 08:18,2026-03-08 08:18:56,2026-03-08T02:48:56Z,Asia/Kolkata,70.639,mg/nm3,...,63.5,Odisha,CPCB-2024,146.2,79.9,2026-07-23 10:56:00,cems_batch_15.csv,103451,OK,contact Mr. X
5,E114407,PL-11,ST-013,ambient,30-03-2026 19:30,2026-03-30 19:30:57,2026-03-30T14:00:57Z,Asia/Kolkata,127.864,mg/nm3,...,68.7,Karnataka,CPCB-2025,170.2,65.5,2026-07-23 10:56:00,cems_batch_02.csv,14408,contains pii: John Doe,stack access restricted
6,E108881,PL-04,ST-007,stack,19-03-2026 11:05,2026-03-19 11:05:23,2026-03-19T05:35:23Z,Asia/Kolkata,441.111,mg/nm3,...,52.6,Karnataka,CPCB-2025,141.1,84.6,2026-07-23 10:56:00,cems_batch_04.csv,8882,OK,NaN
7,E111524,PL-11,ST-035,stack,24-03-2026 19:24,2026-03-24 19:24:27,2026-03-24T13:54:27Z,Asia/Kolkata,129.840,mg/Nm3,...,64.2,Karnataka,CPCB-2023,72.4,90.5,2026-07-23 10:56:00,cems_batch_16.csv,11525,inspection note,no issues observed
8,E101606,PL-14,ST-018,stack,04-03-2026 10:07,2026-03-04 10:07:53,2026-03-04T04:37:53Z,Asia/Kolkata,123.836,ug/m3,...,50.0,Karnataka,CPCB-2024,144.5,39.5,2026-07-23 10:56:00,cems_batch_11.csv,1607,inspection note,no issues observed
9,E110447,PL-13,ST-029,stack,22-03-2026 15:50,2026-03-22 15:50:03,2026-03-22T10:20:03Z,Asia/Kolkata,68.047,ug/m3,...,68.8,Maharashtra,CPCB-2023,87.7,40.1,2026-07-23 10:56:00,cems_batch_05.csv,10448,inspection note,no issues observed

In [7]:
df.tail(10)

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS_raw,TS_local,TS_utc,TS_timezone,PM2_5_raw,PM2_5_unit,...,RH_pct,Jurisdiction,Regulation_version,Pollutant_standard_hourly,Pollutant_standard_daily,Ingest_ts,Source_file,Source_row_num,Raw_note,Inspector_notes
15240,E100466,PL-08,ST-015,stack,01-03-2026 23:59,2026-03-01 23:59:25,2026-03-01T18:29:25Z,Asia/Kolkata,102.304,ug/m3,...,78.0,Tamil Nadu,CPCB-2025,104.0,88.5,2026-07-23 10:56:00,cems_batch_05.csv,467,manual note,NaN
15241,E106265,PL-14,ST-001,stack,14-03-2026 02:31,2026-03-14 02:31:13,2026-03-13T21:01:13Z,Asia/Kolkata,202.027,mg/Nm3,...,40.9,Tamil Nadu,CPCB-2024,107.9,32.6,2026-07-23 10:56:00,cems_batch_07.csv,6266,OK,NaN
15242,E105734,PL-01,ST-002,ambient,12-03-2026 23:44,2026-03-12 23:44:25,2026-03-12T18:14:25Z,Asia/Kolkata,74.634,UG/M3,...,23.5,Tamil Nadu,CPCB-2025,167.8,73.9,2026-07-23 10:56:00,cems_batch_16.csv,5735,manual note,NaN
15243,E111284,PL-12,ST-027,stack,24-03-2026 08:03,2026-03-24 08:03:31,2026-03-24T02:33:31Z,Asia/Kolkata,65.841,ug/m3,...,36.8,Odisha,CPCB-2025,95.2,43.1,2026-07-23 10:56:00,cems_batch_20.csv,11285,contains pii: John Doe,NaN
15244,E111964,PL-16,ST-022,ambient,25-03-2026 18:51,2026-03-25 18:51:23,2026-03-25T13:21:23Z,Asia/Kolkata,77.146,UG/M3,...,27.1,Karnataka,CPCB-2025,104.8,52.9,2026-07-23 10:56:00,cems_batch_19.csv,11965,inspection note,contact Mr. X
15245,E105191,PL-13,ST-029,stack,11-03-2026 20:28,2026-03-11 20:28:07,2026-03-11T14:58:07Z,Asia/Kolkata,158.509,Âµg/mÂ³,...,91.7,Tamil Nadu,CPCB-2025,130.7,79.3,2026-07-23 10:56:00,cems_batch_01.csv,5192,contains pii: John Doe,stack access restricted
15246,E113418,PL-04,ST-035,stack,28-03-2026 17:28,2026-03-28 17:28:02,2026-03-28T11:58:02Z,Asia/Kolkata,44.551,Âµg/mÂ³,...,68.8,Maharashtra,CPCB-2023,59.7,41.0,2026-07-23 10:56:00,cems_batch_04.csv,13419,OK,contact Mr. X
15247,E105390,PL-17,ST-010,stack,2026/03/12 07:11:04,2026-03-12 07:11:04,2026-03-12T01:41:04Z,Asia/Kolkata,-355.883,Âµg/mÂ³,...,84.8,Odisha,CPCB-2024,51.7,89.5,2026-07-23 10:56:00,cems_batch_13.csv,5391,inspection note,contact Mr. X
15248,E100860,PL-01,ST-002,stack,02-03-2026 19:14,2026-03-02 19:14:07,2026-03-02T13:44:07Z,Asia/Kolkata,175.051,ug/m3,...,74.7,Karnataka,CPCB-2023,179.3,40.2,2026-07-23 10:56:00,cems_batch_08.csv,861,contains pii: John Doe,no issues observed
15249,E107270,PL-10,ST-036,stack,16-03-2026 04:39,2026-03-16 04:39:03,2026-03-15T23:09:03Z,Asia/Kolkata,89.395,Âµg/mÂ³,...,60.9,Odisha,CPCB-2023,101.4,40.3,2026-07-23 10:56:00,cems_batch_14.csv,7271,inspection note,contact Mr. X

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15250 entries, 0 to 15249
Data columns (total 52 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Record_ID                  15250 non-null  object
 1   Plant_ID                   15250 non-null  object
 2   Stack_ID                   15250 non-null  object
 3   Source_Type                15250 non-null  object
 4   TS_raw                     15250 non-null  object
 5   TS_local                   15250 non-null  object
 6   TS_utc                     15250 non-null  object
 7   TS_timezone                15250 non-null  object
 8   PM2_5_raw                  15250 non-null  float64
 9   PM2_5_unit                 15250 non-null  object
 10  SO2_raw                    15250 non-null  float64
 11  SO2_unit                   15250 non-null  object
 12  NOx_raw                    15250 non-null  float64
 13  NOx_unit                   15250 non-null  object
 14  LatLon_raw                 15250 non-null  object
 15  Lat                        15250 non-null  float64
 16  Lon                        15250 non-null  float64
 17  Status_raw                 15250 non-null  object
 18  Status_norm                15250 non-null  object
 19  Sensor_serial              15250 non-null  object
 20  Instrument_type            15250 non-null  object
 21  Manufacturer               15250 non-null  object
 22  Calibration_span_factor    15250 non-null  float64
 23  Calibration_zero_offset    15250 non-null  float64
 24  Last_calibration_ts        10728 non-null  object
 25  Next_calibration_due       10638 non-null  object
 26  LOD_PM2_5                  15250 non-null  float64
 27  LOD_SO2                    15250 non-null  float64
 28  LOD_NOx                    15250 non-null  float64
 29  Maintenance_event_ID       1263 non-null   object
 30  Maintenance_start_ts       1263 non-null   object
 31  Maintenance_end_ts         1263 non-null   object
 32  Maintenance_type           1263 non-null   object
 33  Maintenance_notes          936 non-null    object
 34  Lab_sample_ID              2343 non-null   object
 35  Lab_received_ts            2343 non-null   object
 36  Lab_result_entry_ts        2343 non-null   object
 37  Analyst_ID                 2343 non-null   object
 38  Double_entry_check_flag    2343 non-null   float64
 39  Wind_speed_m_s             15250 non-null  float64
 40  Wind_dir_deg               15250 non-null  float64
 41  Temp_C                     15250 non-null  float64
 42  RH_pct                     15250 non-null  float64
 43  Jurisdiction               15250 non-null  object
 44  Regulation_version         15250 non-null  object
 45  Pollutant_standard_hourly  15250 non-null  float64
 46  Pollutant_standard_daily   15250 non-null  float64
 47  Ingest_ts                  15250 non-null  object
 48  Source_file                15250 non-null  object
 49  Source_row_num             15250 non-null  int64
 50  Raw_note                   15250 non-null  object
 51  Inspector_notes            11433 non-null  object
dtypes: float64(17), int64(1), object(34)
memory usage: 6.1+ MB

In [9]:
df.describe()

,PM2_5_raw,SO2_raw,NOx_raw,Lat,Lon,Calibration_span_factor,Calibration_zero_offset,LOD_PM2_5,LOD_SO2,LOD_NOx,Double_entry_check_flag,Wind_speed_m_s,Wind_dir_deg,Temp_C,RH_pct,Pollutant_standard_hourly,Pollutant_standard_daily,Source_row_num
count,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000,2343.000000,15250.000000,15250.00000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000
mean,138.304188,580.058914,54.576653,14.428743,79.130511,1.014804,0.014771,5.451327,3.002061,4.514294,0.506189,7.539314,181.31177,25.964852,59.093934,125.356728,62.302013,9139.850361
std,114.482555,7354.867274,38.871154,0.816305,1.925564,0.037495,1.157080,2.590740,1.152714,2.021368,0.500068,4.352935,104.24402,9.202020,22.414288,43.183287,21.647594,13438.234251
min,-586.989000,3.919000,0.000000,13.128350,76.044753,0.950000,-1.999100,1.000000,1.000000,1.000000,0.000000,0.000000,0.00000,10.000000,20.000000,50.000000,25.000000,1.000000
25%,67.182000,20.074500,28.537500,13.877838,77.540239,0.982400,-0.980800,3.200000,2.000000,2.760000,0.000000,3.700000,91.40000,18.000000,39.600000,88.000000,43.025000,3813.250000
50%,110.085500,30.039500,44.543500,14.313993,78.459697,1.014800,0.025900,5.440000,3.010000,4.520000,1.000000,7.585000,181.40000,25.950000,59.200000,125.300000,62.200000,7625.500000
75%,176.818500,45.183500,68.404750,15.125737,80.987454,1.047200,1.017350,7.680000,3.990000,6.270000,1.000000,11.340000,272.90000,33.800000,78.300000,162.700000,80.900000,11437.750000
max,1336.658000,99999.000000,436.078000,15.954814,82.512415,1.080000,1.999500,10.000000,5.000000,8.000000,1.000000,15.000000,360.00000,42.000000,98.000000,200.000000,100.000000,202715.000000

In [10]:
df.describe(include='object')

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS_raw,TS_local,TS_utc,TS_timezone,PM2_5_unit,SO2_unit,...,Lab_sample_ID,Lab_received_ts,Lab_result_entry_ts,Analyst_ID,Jurisdiction,Regulation_version,Ingest_ts,Source_file,Raw_note,Inspector_notes
count,15250,15250,15250,15250,15250,15250,15250,15250,15250,15250,...,2343,2343,2343,2343,15250,15250,15250,15250,15250,11433
unique,15000,20,25,4,12789,14961,14961,1,5,5,...,2298,2300,2301,2045,4,3,1,20,4,3
top,E102042,PL-03,ST-007,stack,10-03-2026 21:57,2026-03-06 11:12:07,2026-03-06T05:42:07Z,Asia/Kolkata,UG/M3,UG/M3,...,LS834358,2026-03-19 10:24:10,2026-03-30 14:40:31,AN5644,Maharashtra,CPCB-2023,2026-07-23 10:56:00,cems_batch_17.csv,OK,contact Mr. X
freq,3,819,1184,8358,5,3,3,15250,3167,3167,...,2,2,2,4,3914,5096,15250,801,3860,3871

In [12]:
df.shape

(15250, 52)

In [13]:
df.columns

Index(['Record_ID', 'Plant_ID', 'Stack_ID', 'Source_Type', 'TS_raw',
       'TS_local', 'TS_utc', 'TS_timezone', 'PM2_5_raw', 'PM2_5_unit',
       'SO2_raw', 'SO2_unit', 'NOx_raw', 'NOx_unit', 'LatLon_raw', 'Lat',
       'Lon', 'Status_raw', 'Status_norm', 'Sensor_serial', 'Instrument_type',
       'Manufacturer', 'Calibration_span_factor', 'Calibration_zero_offset',
       'Last_calibration_ts', 'Next_calibration_due', 'LOD_PM2_5', 'LOD_SO2',
       'LOD_NOx', 'Maintenance_event_ID', 'Maintenance_start_ts',
       'Maintenance_end_ts', 'Maintenance_type', 'Maintenance_notes',
       'Lab_sample_ID', 'Lab_received_ts', 'Lab_result_entry_ts', 'Analyst_ID',
       'Double_entry_check_flag', 'Wind_speed_m_s', 'Wind_dir_deg', 'Temp_C',
       'RH_pct', 'Jurisdiction', 'Regulation_version',
       'Pollutant_standard_hourly', 'Pollutant_standard_daily', 'Ingest_ts',
       'Source_file', 'Source_row_num', 'Raw_note', 'Inspector_notes'],
      dtype='object')

In [21]:
print(df.columns.tolist())

['Record_ID', 'Plant_ID', 'Stack_ID', 'Source_Type', 'TS_raw', 'TS_local', 'TS_utc', 'TS_timezone', 'PM2_5_raw', 'PM2_5_unit', 'SO2_raw', 'SO2_unit', 'NOx_raw', 'NOx_unit', 'LatLon_raw', 'Lat', 'Lon', 'Status_raw', 'Status_norm', 'Sensor_serial', 'Instrument_type', 'Manufacturer', 'Calibration_span_factor', 'Calibration_zero_offset', 'Last_calibration_ts', 'Next_calibration_due', 'LOD_PM2_5', 'LOD_SO2', 'LOD_NOx', 'Maintenance_event_ID', 'Maintenance_start_ts', 'Maintenance_end_ts', 'Maintenance_type', 'Maintenance_notes', 'Lab_sample_ID', 'Lab_received_ts', 'Lab_result_entry_ts', 'Analyst_ID', 'Double_entry_check_flag', 'Wind_speed_m_s', 'Wind_dir_deg', 'Temp_C', 'RH_pct', 'Jurisdiction', 'Regulation_version', 'Pollutant_standard_hourly', 'Pollutant_standard_daily', 'Ingest_ts', 'Source_file', 'Source_row_num', 'Raw_note', 'Inspector_notes']